'use strict';
const angular = require('angular');
const uiRouter = require('angular-ui-router');
const firebase = require('firebase');

import routes from './general.routes';

export class GeneralComponent {
  /*@ngInject*/

  constructor($scope, $state, Auth) {

    var numbers = [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10];
    $scope.loading = true;

    if($state.params.id) {
      firebase.database()
        .ref('records/general/' + $state.params.id)
        .once('value')
        .then(function(datas) {
          $scope.writeRecord = function() {
            firebase.database().ref('records/general/' + $state.params.id).set({
              userId: datas.val().userId,
              patientId: $scope.datas.patientId,
              birthdate: $scope.datas.birthdate,
              date: $scope.datas.date,
              profession: $scope.datas.profession || null,
              gender: $scope.datas.gender || null,
              checkup: $scope.datas.checkup || null,
              reasons: $scope.datas.reasons || null,
              pain: $scope.datas.pain || null,
              firstpain: $scope.datas.firstpain || null,
              bottom: $scope.datas.bottom || null,
              peak: $scope.datas.peak || null,
              startdate: $scope.datas.startdate || null,
              quality: $scope.datas.quality || null,
              time: $scope.datas.time || null,
              frequency: $scope.datas.frequency || null,
              startingCycle: $scope.datas.startingCycle || null,
              modifiedBy: $scope.datas.modifiedBy || null,
              treatment: $scope.datas.treatment || null,
              dn4: $scope.datas.dn4 || null,
              family: $scope.datas.family || null,
              social: $scope.datas.social || null,
              professional: $scope.datas.professional || null,
              anxiety: $scope.datas.anxiety || null,
              depression: $scope.datas.depression || null,
              stress: $scope.datas.stress || null,
              rachid: $scope.datas.rachid || null,
              cephal: $scope.datas.cephal || null,
              apnea: $scope.datas.apnea || null,
              othersysmptoms: $scope.datas.othersysmptoms || null,
              treatment2: $scope.datas.treatment2 || null,
              psqi: $scope.datas.psqi || null,
              isi: $scope.datas.isi || null,
              eyedisorder: $scope.datas.eyedisorder || null,
              onycophagy: $scope.datas.onycophagy || null,
              nibbling: $scope.datas.nibbling || null,
              bruxism: $scope.datas.bruxism || null,
              chewinggum: $scope.datas.chewinggum || null,
              tobacco: $scope.datas.tobacco || null,
              others: $scope.datas.others || null,
              othersText: $scope.datas.othersText || null,
              orolingual: $scope.datas.orolingual || null,
              halloween: $scope.datas.halloween || null,
              friedman: $scope.datas.friedman || null,
              mallampati: $scope.datas.mallampati || null,
              trauma: $scope.datas.trauma || null,
              observations: $scope.datas.observations || null,
              toothref: $scope.datas.toothref || null,
              toothrefOther: $scope.datas.toothrefOther || null,
              toothref2: $scope.datas.toothref2 || null,
              toothref2Other: $scope.datas.toothref2Other || null,
              horizontaloverhang: $scope.datas.horizontaloverhang || null,
              negative1: $scope.datas.negative1 || null,
              verticaloverlap: $scope.datas.verticaloverlap || null,
              negative2: $scope.datas.negative2 || null,
              offset: $scope.datas.offset || null,
              offsetDetail: $scope.datas.offsetDetail || null,
              straight: $scope.datas.straight || null,
              deflectRight: $scope.datas.deflectRight || null,
              deflectLeft: $scope.datas.deflectLeft || null,
              deviationRight: $scope.datas.deviationRight || null,
              deviationLeft: $scope.datas.deviationLeft || null,
              openmouth: $scope.datas.openmouth || null,
              closedmouth: $scope.datas.closedmouth || null,
              blockAtmRight: $scope.datas.blockAtmRight || null,
              blockAtmLeft: $scope.datas.blockAtmLeft || null,
              blockfrequency: $scope.datas.blockfrequency || null,
              lastoccurence: $scope.datas.lastoccurence || null,
              atmRight: $scope.datas.atmRight || null,
              atmLeft: $scope.datas.atmLeft || null,
              oimcontact: $scope.datas.oimcontact || null,
              closeteeth: $scope.datas.closeteeth || null,
              chewing: $scope.datas.chewing || null,
              lateralRight: $scope.datas.lateralRight || null,
              lateralLeft: $scope.datas.lateralLeft || null,
              propulsion: $scope.datas.propulsion || null,
              prematured: $scope.datas.prematured || null,
              anteroPosterieur: $scope.datas.anteroPosterieur || null,
              lateral: $scope.datas.lateral || null,
              erosion: $scope.datas.erosion || null,
              attrition: $scope.datas.attrition || null,
              abrasion: $scope.datas.abrasion || null,
              plause: $scope.datas.plause || null,
              incisifinfo: $scope.datas.incisifinfo || null,
              diagnostic: $scope.datas.diagnostic || null,
              treatmentplan: $scope.datas.treatmentplan || null,
              negative11 : $scope.datas.negative11 || null,
              noInformation11 : $scope.datas.noInformation11 || null,
              negative13 : $scope.datas.negative13 || null,
              noInformation13 : $scope.datas.noInformation13 || null,
              negative15 : $scope.datas.negative15 || null,
              noInformation15 : $scope.datas.noInformation15 || null,
              negative17 : $scope.datas.negative17 || null,
              noInformation17 : $scope.datas.noInformation17 || null,
              stickRPainR : $scope.datas.stickRPainR || null,
              stickRSelectStickR : $scope.datas.stickRSelectStickR || null,
              stickROtherPainStickR : $scope.datas.stickROtherPainStickR || null,
              stickRPainL : $scope.datas.stickRPainL || null,
              stickRSelectStickL : $scope.datas.stickRSelectStickL || null,
              stickROtherPainStickL : $scope.datas.stickROtherPainStickL || null,
              stickLPainR : $scope.datas.stickLPainR || null,
              stickLSelectStickR : $scope.datas.stickLSelectStickR || null,
              stickLOtherPainStickR : $scope.datas.stickLOtherPainStickR || null,
              stickLPainL : $scope.datas.stickLPainL || null,
              stickLSelectStickL : $scope.datas.stickLSelectStickL || null,
              stickLOtherPainStickL : $scope.datas.stickLOtherPainStickL || null,
              ATMOpenRPractitionerClapping: $scope.datas.ATMOpenRPractitionerClapping  || null,
              ATMOpenRPractitionerCrackling: $scope.datas.ATMOpenRPractitionerCrackling || null,
              ATMOpenRPatientClapping: $scope.datas.ATMOpenRPatientClapping  || null,
              ATMOpenRPatientCrackling: $scope.datas.ATMOpenRPatientCrackling || null,
              ATMOpenRPatientPain: $scope.datas.ATMOpenRPatientPain || null,
              ATMOpenRCheckboxUsualPain: $scope.datas.ATMOpenRCheckboxUsualPain || null,
              ATMOpenRSelectUsualPain: $scope.datas.ATMOpenRSelectUsualPain|| null,
              ATMOpenROtherUsualPain: $scope.datas.ATMOpenROtherUsualPain || null,
              ATMOpenLPractitionerClapping: $scope.datas.ATMOpenLPractitionerClapping  || null,
              ATMOpenLPractitionerCrackling: $scope.datas.ATMOpenLPractitionerCrackling || null,
              ATMOpenLPatientClapping: $scope.datas.ATMOpenLPatientClapping  || null,
              ATMOpenLPatientCrackling: $scope.datas.ATMOpenLPatientCrackling || null,
              ATMOpenLPatientPain: $scope.datas.ATMOpenLPatientPain || null,
              ATMOpenLCheckboxUsualPain: $scope.datas.ATMOpenLCheckboxUsualPain || null,
              ATMOpenLSelectUsualPain: $scope.datas.ATMOpenLSelectUsualPain|| null,
              ATMOpenLOtherUsualPain: $scope.datas.ATMOpenLOtherUsualPain || null,
              ATMCloseRPractitionerClapping: $scope.datas.ATMCloseRPractitionerClapping  || null,
              ATMCloseRPractitionerCrackling: $scope.datas.ATMCloseRPractitionerCrackling || null,
              ATMCloseRPatientClapping: $scope.datas.ATMCloseRPatientClapping  || null,
              ATMCloseRPatientCrackling: $scope.datas.ATMCloseRPatientCrackling || null,
              ATMCloseRPatientPain: $scope.datas.ATMCloseRPatientPain || null,
              ATMCloseRCheckboxUsualPain: $scope.datas.ATMCloseRCheckboxUsualPain || null,
              ATMCloseRSelectUsualPain: $scope.datas.ATMCloseRSelectUsualPain|| null,
              ATMCloseROtherUsualPain: $scope.datas.ATMCloseROtherUsualPain || null,
              ATMCloseLPractitionerClapping: $scope.datas.ATMCloseLPractitionerClapping  || null,
              ATMCloseLPractitionerCrackling: $scope.datas.ATMCloseLPractitionerCrackling || null,
              ATMCloseLPatientClapping: $scope.datas.ATMCloseLPatientClapping  || null,
              ATMCloseLPatientCrackling: $scope.datas.ATMCloseLPatientCrackling || null,
              ATMCloseLPatientPain: $scope.datas.ATMCloseLPatientPain || null,
              ATMCloseLCheckboxUsualPain: $scope.datas.ATMCloseLCheckboxUsualPain || null,
              ATMCloseLSelectUsualPain: $scope.datas.ATMCloseLSelectUsualPain|| null,
              ATMCloseLOtherUsualPain: $scope.datas.ATMCloseLOtherUsualPain || null,
              ATMLatLRPractitionerClapping: $scope.datas.ATMLatLRPractitionerClapping  || null,
              ATMLatLRPractitionerCrackling: $scope.datas.ATMLatLRPractitionerCrackling || null,
              ATMLatLRPatientClapping: $scope.datas.ATMLatLRPatientClapping  || null,
              ATMLatLRPatientCrackling: $scope.datas.ATMLatLRPatientCrackling || null,
              ATMLatLRPatientPain: $scope.datas.ATMLatLRPatientPain || null,
              ATMLatLRCheckboxUsualPain: $scope.datas.ATMLatLRCheckboxUsualPain || null,
              ATMLatLRSelectUsualPain: $scope.datas.ATMLatLRSelectUsualPain|| null,
              ATMLatLROtherUsualPain: $scope.datas.ATMLatLROtherUsualPain || null,
              ATMLatLLPractitionerClapping: $scope.datas.ATMLatLLPractitionerClapping  || null,
              ATMLatLLPractitionerCrackling: $scope.datas.ATMLatLLPractitionerCrackling || null,
              ATMLatLLPatientClapping: $scope.datas.ATMLatLLPatientClapping  || null,
              ATMLatLLPatientCrackling: $scope.datas.ATMLatLLPatientCrackling || null,
              ATMLatLLPatientPain: $scope.datas.ATMLatLLPatientPain || null,
              ATMLatLLCheckboxUsualPain: $scope.datas.ATMLatLLCheckboxUsualPain || null,
              ATMLatLLSelectUsualPain: $scope.datas.ATMLatLLSelectUsualPain|| null,
              ATMLatLLOtherUsualPain: $scope.datas.ATMLatLLOtherUsualPain || null,
              ATMLatRRPractitionerClapping: $scope.datas.ATMLatRRPractitionerClapping  || null,
              ATMLatRRPractitionerCrackling: $scope.datas.ATMLatRRPractitionerCrackling || null,
              ATMLatRRPatientClapping: $scope.datas.ATMLatRRPatientClapping  || null,
              ATMLatRRPatientCrackling: $scope.datas.ATMLatRRPatientCrackling || null,
              ATMLatRRPatientPain: $scope.datas.ATMLatRRPatientPain || null,
              ATMLatRRCheckboxUsualPain: $scope.datas.ATMLatRRCheckboxUsualPain || null,
              ATMLatRRSelectUsualPain: $scope.datas.ATMLatRRSelectUsualPain|| null,
              ATMLatRROtherUsualPain: $scope.datas.ATMLatRROtherUsualPain || null,
              ATMLatRLPractitionerClapping: $scope.datas.ATMLatRLPractitionerClapping  || null,
              ATMLatRLPractitionerCrackling: $scope.datas.ATMLatRLPractitionerCrackling || null,
              ATMLatRLPatientClapping: $scope.datas.ATMLatRLPatientClapping  || null,
              ATMLatRLPatientCrackling: $scope.datas.ATMLatRLPatientCrackling || null,
              ATMLatRLPatientPain: $scope.datas.ATMLatRLPatientPain || null,
              ATMLatRLCheckboxUsualPain: $scope.datas.ATMLatRLCheckboxUsualPain || null,
              ATMLatRLSelectUsualPain: $scope.datas.ATMLatRLSelectUsualPain|| null,
              ATMLatRLOtherUsualPain: $scope.datas.ATMLatRLOtherUsualPain || null,
              ATMPropRPractitionerClapping: $scope.datas.ATMPropRPractitionerClapping  || null,
              ATMPropRPractitionerCrackling: $scope.datas.ATMPropRPractitionerCrackling || null,
              ATMPropRPatientClapping: $scope.datas.ATMPropRPatientClapping  || null,
              ATMPropRPatientCrackling: $scope.datas.ATMPropRPatientCrackling || null,
              ATMPropRPatientPain: $scope.datas.ATMPropRPatientPain || null,
              ATMPropRCheckboxUsualPain: $scope.datas.ATMPropRCheckboxUsualPain || null,
              ATMPropRSelectUsualPain: $scope.datas.ATMPropRSelectUsualPain|| null,
              ATMPropROtherUsualPain: $scope.datas.ATMPropROtherUsualPain || null,
              ATMPropLPractitionerClapping: $scope.datas.ATMPropLPractitionerClapping  || null,
              ATMPropLPractitionerCrackling: $scope.datas.ATMPropLPractitionerCrackling || null,
              ATMPropLPatientClapping: $scope.datas.ATMPropLPatientClapping  || null,
              ATMPropLPatientCrackling: $scope.datas.ATMPropLPatientCrackling || null,
              ATMPropLPatientPain: $scope.datas.ATMPropLPatientPain || null,
              ATMPropLCheckboxUsualPain: $scope.datas.ATMPropLCheckboxUsualPain || null,
              ATMPropLSelectUsualPain: $scope.datas.ATMPropLSelectUsualPain|| null,
              ATMPropLOtherUsualPain: $scope.datas.ATMPropLOtherUsualPain || null,
              maxOpenPainOpen: $scope.datas.maxOpenPainOpen || null,
              maxOpenPainCausedR: $scope.datas.maxOpenPainCausedR || null,
              maxOpenSamePainR: $scope.datas.maxOpenSamePainR || null,
              maxOpenSelectR: $scope.datas.maxOpenSelectR || null,
              maxOpenOtherInputR: $scope.datas.maxOpenOtherInputR || null,
              maxOpenPainCausedL: $scope.datas.maxOpenPainCausedL || null,
              maxOpenSamePainL: $scope.datas.maxOpenSamePainL || null,
              maxOpenSelectL: $scope.datas.maxOpenSelectL || null,
              maxOpenOtherInputL: $scope.datas.maxOpenOtherInputL || null,
              maxOpenAssistedPainOpen: $scope.datas.maxOpenAssistedPainOpen || null,
              maxOpenAssistedPainCausedR: $scope.datas.maxOpenAssistedPainCausedR || null,
              maxOpenAssistedSamePainR: $scope.datas.maxOpenAssistedSamePainR || null,
              maxOpenAssistedSelectR: $scope.datas.maxOpenAssistedSelectR || null,
              maxOpenAssistedOtherInputR: $scope.datas.maxOpenAssistedOtherInputR || null,
              maxOpenAssistedPainCausedL: $scope.datas.maxOpenAssistedPainCausedL || null,
              maxOpenAssistedSamePainL: $scope.datas.maxOpenAssistedSamePainL || null,
              maxOpenAssistedSelectL: $scope.datas.maxOpenAssistedSelectL || null,
              maxOpenAssistedOtherInputL: $scope.datas.maxOpenAssistedOtherInputL || null,
              resistanceOpenPainOpen: $scope.datas.resistanceOpenPainOpen || null,
              resistanceOpenPainCausedR: $scope.datas.resistanceOpenPainCausedR || null,
              resistanceOpenSamePainR: $scope.datas.resistanceOpenSamePainR || null,
              resistanceOpenSelectR: $scope.datas.resistanceOpenSelectR || null,
              resistanceOpenOtherInputR: $scope.datas.resistanceOpenOtherInputR || null,
              resistanceOpenPainCausedL: $scope.datas.resistanceOpenPainCausedL || null,
              resistanceOpenSamePainL: $scope.datas.resistanceOpenSamePainL || null,
              resistanceOpenSelectL: $scope.datas.resistanceOpenSelectL || null,
              resistanceOpenOtherInputL: $scope.datas.resistanceOpenOtherInputL || null,
              resistanceClosePainOpen: $scope.datas.resistanceClosePainOpen || null,
              resistanceClosePainCausedR: $scope.datas.resistanceClosePainCausedR || null,
              resistanceCloseSamePainR: $scope.datas.resistanceCloseSamePainR || null,
              resistanceCloseSelectR: $scope.datas.resistanceCloseSelectR || null,
              resistanceCloseOtherInputR: $scope.datas.resistanceCloseOtherInputR || null,
              resistanceClosePainCausedL: $scope.datas.resistanceClosePainCausedL || null,
              resistanceCloseSamePainL: $scope.datas.resistanceCloseSamePainL || null,
              resistanceCloseSelectL: $scope.datas.resistanceCloseSelectL || null,
              resistanceCloseOtherInputL: $scope.datas.resistanceCloseOtherInputL || null,
              latRPainOpen: $scope.datas.latRPainOpen || null,
              latRPainCausedR: $scope.datas.latRPainCausedR || null,
              latRSamePainR: $scope.datas.latRSamePainR || null,
              latRSelectR: $scope.datas.latRSelectR || null,
              latROtherInputR: $scope.datas.latROtherInputR || null,
              latRPainCausedL: $scope.datas.latRPainCausedL || null,
              latRSamePainL: $scope.datas.latRSamePainL || null,
              latRSelectL: $scope.datas.latRSelectL || null,
              latROtherInputL: $scope.datas.latROtherInputL || null,
              latRassistedPainOpen: $scope.datas.latRassistedPainOpen || null,
              latRassistedPainCausedR: $scope.datas.latRassistedPainCausedR || null,
              latRassistedSamePainR: $scope.datas.latRassistedSamePainR || null,
              latRassistedSelectR: $scope.datas.latRassistedSelectR || null,
              latRassistedOtherInputR: $scope.datas.latRassistedOtherInputR || null,
              latRassistedPainCausedL: $scope.datas.latRassistedPainCausedL || null,
              latRassistedSamePainL: $scope.datas.latRassistedSamePainL || null,
              latRassistedSelectL: $scope.datas.latRassistedSelectL || null,
              latRassistedOtherInputL: $scope.datas.latRassistedOtherInputL || null,
              resistanceLatRPainOpen: $scope.datas.resistanceLatRPainOpen || null,
              resistanceLatRPainCausedR: $scope.datas.resistanceLatRPainCausedR || null,
              resistanceLatRSamePainR: $scope.datas.resistanceLatRSamePainR || null,
              resistanceLatRSelectR: $scope.datas.resistanceLatRSelectR || null,
              resistanceLatROtherInputR: $scope.datas.resistanceLatROtherInputR || null,
              resistanceLatRPainCausedL: $scope.datas.resistanceLatRPainCausedL || null,
              resistanceLatRSamePainL: $scope.datas.resistanceLatRSamePainL || null,
              resistanceLatRSelectL: $scope.datas.resistanceLatRSelectL || null,
              resistanceLatROtherInputL: $scope.datas.resistanceLatROtherInputL || null,
              latLassistedPainOpen: $scope.datas.latLassistedPainOpen || null,
              latLassistedPainCausedR: $scope.datas.latLassistedPainCausedR || null,
              latLassistedSamePainR: $scope.datas.latLassistedSamePainR || null,
              latLassistedSelectR: $scope.datas.latLassistedSelectR || null,
              latLassistedOtherInputR: $scope.datas.latLassistedOtherInputR || null,
              latLassistedPainCausedL: $scope.datas.latLassistedPainCausedL || null,
              latLassistedSamePainL: $scope.datas.latLassistedSamePainL || null,
              latLassistedSelectL: $scope.datas.latLassistedSelectL || null,
              latLassistedOtherInputL: $scope.datas.latLassistedOtherInputL || null,
              resistanceLatLPainOpen: $scope.datas.resistanceLatLPainOpen || null,
              resistanceLatLPainCausedR: $scope.datas.resistanceLatLPainCausedR || null,
              resistanceLatLSamePainR: $scope.datas.resistanceLatLSamePainR || null,
              resistanceLatLSelectR: $scope.datas.resistanceLatLSelectR || null,
              resistanceLatLOtherInputR: $scope.datas.resistanceLatLOtherInputR || null,
              resistanceLatLPainCausedL: $scope.datas.resistanceLatLPainCausedL || null,
              resistanceLatLSamePainL: $scope.datas.resistanceLatLSamePainL || null,
              resistanceLatLSelectL: $scope.datas.resistanceLatLSelectL || null,
              resistanceLatLOtherInputL: $scope.datas.resistanceLatLOtherInputL || null,
              tablePropulsionPainOpen: $scope.datas.tablePropulsionPainOpen || null,
              tablePropulsionPainCausedR: $scope.datas.tablePropulsionPainCausedR || null,
              tablePropulsionSamePainR: $scope.datas.tablePropulsionSamePainR || null,
              tablePropulsionSelectR: $scope.datas.tablePropulsionSelectR || null,
              tablePropulsionOtherInputR: $scope.datas.tablePropulsionOtherInputR || null,
              tablePropulsionPainCausedL: $scope.datas.tablePropulsionPainCausedL || null,
              tablePropulsionSamePainL: $scope.datas.tablePropulsionSamePainL || null,
              tablePropulsionSelectL: $scope.datas.tablePropulsionSelectL || null,
              tablePropulsionOtherInputL: $scope.datas.tablePropulsionOtherInputL || null,
              resistancePropPainOpen: $scope.datas.resistancePropPainOpen || null,
              resistancePropPainCausedR: $scope.datas.resistancePropPainCausedR || null,
              resistancePropSamePainR: $scope.datas.resistancePropSamePainR || null,
              resistancePropSelectR: $scope.datas.resistancePropSelectR || null,
              resistancePropOtherInputR: $scope.datas.resistancePropOtherInputR || null,
              resistancePropPainCausedL: $scope.datas.resistancePropPainCausedL || null,
              resistancePropSamePainL: $scope.datas.resistancePropSamePainL || null,
              resistancePropSelectL: $scope.datas.resistancePropSelectL || null,
              resistancePropOtherInputL: $scope.datas.resistancePropOtherInputL || null,
              palpationMuscles: $scope.datas.palpationMuscles  || null,
              painOpen: $scope.datas.noPainOpen  || null,
              headache: $scope.datas.headache  || null,
              whichMotionHeadache: $scope.datas.whichMotionHeadache  || null,
              tmpPostPainCausedR: $scope.datas.tmpPostPainCausedR || null,
              tmpPostSamePainR: $scope.datas.tmpPostSamePainR || null,
              tmpPostSelectR: $scope.datas.tmpPostSelectR || null,
              tmpPostOtherInputR: $scope.datas.tmpPostOtherInputR || null,
              tmpPostPainCausedL: $scope.datas.tmpPostPainCausedL || null,
              tmpPostSamePainL: $scope.datas.tmpPostSamePainL || null,
              tmpPostSelectL: $scope.datas.tmpPostSelectL || null,
              tmpPostOtherInputL: $scope.datas.tmpPostOtherInputL || null,
              tmpAvgPainCausedR: $scope.datas.tmpAvgPainCausedR || null,
              tmpAvgSamePainR: $scope.datas.tmpAvgSamePainR || null,
              tmpAvgSelectR: $scope.datas.tmpAvgSelectR || null,
              tmpAvgOtherInputR: $scope.datas.tmpAvgOtherInputR || null,
              tmpAvgPainCausedL: $scope.datas.tmpAvgPainCausedL || null,
              tmpAvgSamePainL: $scope.datas.tmpAvgSamePainL || null,
              tmpAvgSelectL: $scope.datas.tmpAvgSelectL || null,
              tmpAvgOtherInputL: $scope.datas.tmpAvgOtherInputL || null,
              tmpAntPainCausedR: $scope.datas.tmpAntPainCausedR || null,
              tmpAntSamePainR: $scope.datas.tmpAntSamePainR || null,
              tmpAntSelectR: $scope.datas.tmpAntSelectR || null,
              tmpAntOtherInputR: $scope.datas.tmpAntOtherInputR || null,
              tmpAntPainCausedL: $scope.datas.tmpAntPainCausedL || null,
              tmpAntSamePainL: $scope.datas.tmpAntSamePainL || null,
              tmpAntSelectL: $scope.datas.tmpAntSelectL || null,
              tmpAntOtherInputL: $scope.datas.tmpAntOtherInputL || null,
              massageAnglePainCausedR: $scope.datas.massageAnglePainCausedR || null,
              massageAngleSamePainR: $scope.datas.massageAngleSamePainR || null,
              massageAngleSelectR: $scope.datas.massageAngleSelectR || null,
              massageAngleOtherInputR: $scope.datas.massageAngleOtherInputR || null,
              massageAnglePainCausedL: $scope.datas.massageAnglePainCausedL || null,
              massageAngleSamePainL: $scope.datas.massageAngleSamePainL || null,
              massageAngleSelectL: $scope.datas.massageAngleSelectL || null,
              massageAngleOtherInputL: $scope.datas.massageAngleOtherInputL || null,
              massageBodyPainCausedR: $scope.datas.massageBodyPainCausedR || null,
              massageBodySamePainR: $scope.datas.massageBodySamePainR || null,
              massageBodySelectR: $scope.datas.massageBodySelectR || null,
              massageBodyOtherInputR: $scope.datas.massageBodyOtherInputR || null,
              massageBodyPainCausedL: $scope.datas.massageBodyPainCausedL || null,
              massageBodySamePainL: $scope.datas.massageBodySamePainL || null,
              massageBodySelectL: $scope.datas.massageBodySelectL || null,
              massageBodyOtherInputL: $scope.datas.massageBodyOtherInputL || null,
              massageInsertPainCausedR: $scope.datas.massageInsertPainCausedR || null,
              massageInsertSamePainR: $scope.datas.massageInsertSamePainR || null,
              massageInsertSelectR: $scope.datas.massageInsertSelectR || null,
              massageInsertOtherInputR: $scope.datas.massageInsertOtherInputR || null,
              massageInsertPainCausedL: $scope.datas.massageInsertPainCausedL || null,
              massageInsertSamePainL: $scope.datas.massageInsertSamePainL || null,
              massageInsertSelectL: $scope.datas.massageInsertSelectL || null,
              massageInsertOtherInputL: $scope.datas.massageInsertOtherInputL || null,
              sidePolePainCausedR: $scope.datas.sidePolePainCausedR || null,
              sidePoleSamePainR: $scope.datas.sidePoleSamePainR || null,
              sidePoleSelectR: $scope.datas.sidePoleSelectR || null,
              sidePoleOtherInputR: $scope.datas.sidePoleOtherInputR || null,
              sidePolePainCausedL: $scope.datas.sidePolePainCausedL || null,
              sidePoleSamePainL: $scope.datas.sidePoleSamePainL || null,
              sidePoleSelectL: $scope.datas.sidePoleSelectL || null,
              sidePoleOtherInputL: $scope.datas.sidePoleOtherInputL || null,
              aroundPolePainCausedR: $scope.datas.aroundPolePainCausedR || null,
              aroundPoleSamePainR: $scope.datas.aroundPoleSamePainR || null,
              aroundPoleSelectR: $scope.datas.aroundPoleSelectR || null,
              aroundPoleOtherInputR: $scope.datas.aroundPoleOtherInputR || null,
              aroundPolePainCausedL: $scope.datas.aroundPolePainCausedL || null,
              aroundPoleSamePainL: $scope.datas.aroundPoleSamePainL || null,
              aroundPoleSelectL: $scope.datas.aroundPoleSelectL || null,
              aroundPoleOtherInputL: $scope.datas.aroundPoleOtherInputL || null,
              otherMuscleMasticatorsPainCausedR: $scope.datas.otherMuscleMasticatorsPainCausedR || null,
              otherMuscleMasticatorsSamePainR: $scope.datas.otherMuscleMasticatorsSamePainR || null,
              otherMuscleMasticatorsSelectR: $scope.datas.otherMuscleMasticatorsSelectR || null,
              otherMuscleMasticatorsOtherInputR: $scope.datas.otherMuscleMasticatorsOtherInputR || null,
              otherMuscleMasticatorsPainCausedL: $scope.datas.otherMuscleMasticatorsPainCausedL || null,
              otherMuscleMasticatorsSamePainL: $scope.datas.otherMuscleMasticatorsSamePainL || null,
              otherMuscleMasticatorsSelectL: $scope.datas.otherMuscleMasticatorsSelectL || null,
              otherMuscleMasticatorsOtherInputL: $scope.datas.otherMuscleMasticatorsOtherInputL || null,
              digastricMDPainCausedR: $scope.datas.digastricMDPainCausedR || null,
              digastricMDSamePainR: $scope.datas.digastricMDSamePainR || null,
              digastricMDSelectR: $scope.datas.digastricMDSelectR || null,
              digastricMDOtherInputR: $scope.datas.digastricMDOtherInputR || null,
              digastricMDPainCausedL: $scope.datas.digastricMDPainCausedL || null,
              digastricMDSamePainL: $scope.datas.digastricMDSamePainL || null,
              digastricMDSelectL: $scope.datas.digastricMDSelectL || null,
              digastricMDOtherInputL: $scope.datas.digastricMDOtherInputL || null,
              PterygoidMedialPainCausedR: $scope.datas.PterygoidMedialPainCausedR || null,
              PterygoidMedialSamePainR: $scope.datas.PterygoidMedialSamePainR || null,
              PterygoidMedialSelectR: $scope.datas.PterygoidMedialSelectR || null,
              PterygoidMedialOtherInputR: $scope.datas.PterygoidMedialOtherInputR || null,
              PterygoidMedialPainCausedL: $scope.datas.PterygoidMedialPainCausedL || null,
              PterygoidMedialSamePainL: $scope.datas.PterygoidMedialSamePainL || null,
              PterygoidMedialSelectL: $scope.datas.PterygoidMedialSelectL || null,
              PterygoidMedialOtherInputL: $scope.datas.PterygoidMedialOtherInputL || null,
              PterygoidAreaSidePainCausedR: $scope.datas.PterygoidAreaSidePainCausedR || null,
              PterygoidAreaSideSamePainR: $scope.datas.PterygoidAreaSideSamePainR || null,
              PterygoidAreaSideSelectR: $scope.datas.PterygoidAreaSideSelectR || null,
              PterygoidAreaSideOtherInputR: $scope.datas.PterygoidAreaSideOtherInputR || null,
              PterygoidAreaSidePainCausedL: $scope.datas.PterygoidAreaSidePainCausedL || null,
              PterygoidAreaSideSamePainL: $scope.datas.PterygoidAreaSideSamePainL || null,
              PterygoidAreaSideSelectL: $scope.datas.PterygoidAreaSideSelectL || null,
              PterygoidAreaSideOtherInputL: $scope.datas.PterygoidAreaSideOtherInputL || null,
              TendonTmpPainCausedR: $scope.datas.TendonTmpPainCausedR || null,
              TendonTmpSamePainR: $scope.datas.TendonTmpSamePainR || null,
              TendonTmpSelectR: $scope.datas.TendonTmpSelectR || null,
              TendonTmpOtherInputR: $scope.datas.TendonTmpOtherInputR || null,
              TendonTmpPainCausedL: $scope.datas.TendonTmpPainCausedL || null,
              TendonTmpSamePainL: $scope.datas.TendonTmpSamePainL || null,
              TendonTmpSelectL: $scope.datas.TendonTmpSelectL || null,
              TendonTmpOtherInputL: $scope.datas.TendonTmpOtherInputL || null,
              otherMusclesCervicoPainCausedR: $scope.datas.otherMusclesCervicoPainCausedR || null,
              otherMusclesCervicoSamePainR: $scope.datas.otherMusclesCervicoSamePainR || null,
              otherMusclesCervicoSelectR: $scope.datas.otherMusclesCervicoSelectR || null,
              otherMusclesCervicoOtherInputR: $scope.datas.otherMusclesCervicoOtherInputR || null,
              otherMusclesCervicoPainCausedL: $scope.datas.otherMusclesCervicoPainCausedL || null,
              otherMusclesCervicoSamePainL: $scope.datas.otherMusclesCervicoSamePainL || null,
              otherMusclesCervicoSelectL: $scope.datas.otherMusclesCervicoSelectL || null,
              otherMusclesCervicoOtherInputL: $scope.datas.otherMusclesCervicoOtherInputL || null,
              mastoidSidePainCausedR: $scope.datas.mastoidSidePainCausedR || null,
              mastoidSideSamePainR: $scope.datas.mastoidSideSamePainR || null,
              mastoidSideSelectR: $scope.datas.mastoidSideSelectR || null,
              mastoidSideOtherInputR: $scope.datas.mastoidSideOtherInputR || null,
              mastoidSidePainCausedL: $scope.datas.mastoidSidePainCausedL || null,
              mastoidSideSamePainL: $scope.datas.mastoidSideSamePainL || null,
              mastoidSideSelectL: $scope.datas.mastoidSideSelectL || null,
              mastoidSideOtherInputL: $scope.datas.mastoidSideOtherInputL || null,
              tableTrapezePainCausedR: $scope.datas.tableTrapezePainCausedR || null,
              tableTrapezeSamePainR: $scope.datas.tableTrapezeSamePainR || null,
              tableTrapezeSelectR: $scope.datas.tableTrapezeSelectR || null,
              tableTrapezeOtherInputR: $scope.datas.tableTrapezeOtherInputR || null,
              tableTrapezePainCausedL: $scope.datas.tableTrapezePainCausedL || null,
              tableTrapezeSamePainL: $scope.datas.tableTrapezeSamePainL || null,
              tableTrapezeSelectL: $scope.datas.tableTrapezeSelectL || null,
              tableTrapezeOtherInputL: $scope.datas.tableTrapezeOtherInputL || null
            });
          }
          $scope.$apply(function(){
            $scope.datas = datas.val();
            $scope.loading = false;
          });
        });
    } else {
      Auth.getCurrentUser().then(function(result) {
        var userId = result._id;
        $scope.datas = {}
        $scope.writeRecord = function() {
          firebase.database().ref('records/general').push({
            userId: userId,
            patientId: $scope.datas.patientId,
            birthdate: $scope.datas.birthdate,
            date: $scope.datas.date,
            profession: $scope.datas.profession || null,
            gender: $scope.datas.gender || null,
            checkup: $scope.datas.checkup || null,
            reasons: $scope.datas.reasons || null,
            pain: $scope.datas.pain || null,
            firstpain: $scope.datas.firstpain || null,
            bottom: $scope.datas.bottom || null,
            peak: $scope.datas.peak || null,
            startdate: $scope.datas.startdate || null,
            quality: $scope.datas.quality || null,
            time: $scope.datas.time || null,
            frequency: $scope.datas.frequency || null,
            startingCycle: $scope.datas.startingCycle || null,
            modifiedBy: $scope.datas.modifiedBy || null,
            treatment: $scope.datas.treatment || null,
            dn4: $scope.datas.dn4 || null,
            family: $scope.datas.family || null,
            social: $scope.datas.social || null,
            professional: $scope.datas.professional || null,
            anxiety: $scope.datas.anxiety || null,
            depression: $scope.datas.depression || null,
            stress: $scope.datas.stress || null,
            rachid: $scope.datas.rachid || null,
            cephal: $scope.datas.cephal || null,
            apnea: $scope.datas.apnea || null,
            othersysmptoms: $scope.datas.othersysmptoms || null,
            treatment2: $scope.datas.treatment2 || null,
            psqi: $scope.datas.psqi || null,
            isi: $scope.datas.isi || null,
            eyedisorder: $scope.datas.eyedisorder || null,
            onycophagy: $scope.datas.onycophagy || null,
            nibbling: $scope.datas.nibbling || null,
            bruxism: $scope.datas.bruxism || null,
            chewinggum: $scope.datas.chewinggum || null,
            tobacco: $scope.datas.tobacco || null,
            others: $scope.datas.others || null,
            othersText: $scope.datas.othersText || null,
            orolingual: $scope.datas.orolingual || null,
            halloween: $scope.datas.halloween || null,
            friedman: $scope.datas.friedman || null,
            mallampati: $scope.datas.mallampati || null,
            trauma: $scope.datas.trauma || null,
            observations: $scope.datas.observations || null,
            toothref: $scope.datas.toothref || null,
            toothrefOther: $scope.datas.toothrefOther || null,
            toothref2: $scope.datas.toothref2 || null,
            toothref2Other: $scope.datas.toothref2Other || null,
            horizontaloverhang: $scope.datas.horizontaloverhang || null,
            negative1: $scope.datas.negative1 || null,
            verticaloverlap: $scope.datas.verticaloverlap || null,
            negative2: $scope.datas.negative2 || null,
            offset: $scope.datas.offset || null,
            offsetDetail: $scope.datas.offsetDetail || null,
            straight: $scope.datas.straight || null,
            deflectRight: $scope.datas.deflectRight || null,
            deflectLeft: $scope.datas.deflectLeft || null,
            deviationRight: $scope.datas.deviationRight || null,
            deviationLeft: $scope.datas.deviationLeft || null,
            openmouth: $scope.datas.openmouth || null,
            closedmouth: $scope.datas.closedmouth || null,
            blockAtmRight: $scope.datas.blockAtmRight || null,
            blockAtmLeft: $scope.datas.blockAtmLeft || null,
            blockfrequency: $scope.datas.blockfrequency || null,
            lastoccurence: $scope.datas.lastoccurence || null,
            atmRight: $scope.datas.atmRight || null,
            atmLeft: $scope.datas.atmLeft || null,
            oimcontact: $scope.datas.oimcontact || null,
            closeteeth: $scope.datas.closeteeth || null,
            chewing: $scope.datas.chewing || null,
            lateralRight: $scope.datas.lateralRight || null,
            lateralLeft: $scope.datas.lateralLeft || null,
            propulsion: $scope.datas.propulsion || null,
            prematured: $scope.datas.prematured || null,
            anteroPosterieur: $scope.datas.anteroPosterieur || null,
            lateral: $scope.datas.lateral || null,
            erosion: $scope.datas.erosion || null,
            attrition: $scope.datas.attrition || null,
            abrasion: $scope.datas.abrasion || null,
            plause: $scope.datas.plause || null,
            incisifinfo: $scope.datas.incisifinfo || null,
            diagnostic: $scope.datas.diagnostic || null,
            treatmentplan: $scope.datas.treatmentplan || null,
            negative11 : $scope.datas.negative11 || null,
            noInformation11 : $scope.datas.noInformation11 || null,
            negative13 : $scope.datas.negative13 || null,
            noInformation13 : $scope.datas.noInformation13 || null,
            negative15 : $scope.datas.negative15 || null,
            noInformation15 : $scope.datas.noInformation15 || null,
            negative17 : $scope.datas.negative17 || null,
            noInformation17 : $scope.datas.noInformation17 || null,
            stickRPainR : $scope.datas.stickRPainR || null,
            stickRSelectStickR : $scope.datas.stickRSelectStickR || null,
            stickROtherPainStickR : $scope.datas.stickROtherPainStickR || null,
            stickRPainL : $scope.datas.stickRPainL || null,
            stickRSelectStickL : $scope.datas.stickRSelectStickL || null,
            stickROtherPainStickL : $scope.datas.stickROtherPainStickL || null,
            stickLPainR : $scope.datas.stickLPainR || null,
            stickLSelectStickR : $scope.datas.stickLSelectStickR || null,
            stickLOtherPainStickR : $scope.datas.stickLOtherPainStickR || null,
            stickLPainL : $scope.datas.stickLPainL || null,
            stickLSelectStickL : $scope.datas.stickLSelectStickL || null,
            stickLOtherPainStickL : $scope.datas.stickLOtherPainStickL || null,
            ATMOpenRPractitionerClapping: $scope.datas.ATMOpenRPractitionerClapping  || null,
            ATMOpenRPractitionerCrackling: $scope.datas.ATMOpenRPractitionerCrackling || null,
            ATMOpenRPatientClapping: $scope.datas.ATMOpenRPatientClapping  || null,
            ATMOpenRPatientCrackling: $scope.datas.ATMOpenRPatientCrackling || null,
            ATMOpenRPatientPain: $scope.datas.ATMOpenRPatientPain || null,
            ATMOpenRCheckboxUsualPain: $scope.datas.ATMOpenRCheckboxUsualPain || null,
            ATMOpenRSelectUsualPain: $scope.datas.ATMOpenRSelectUsualPain|| null,
            ATMOpenROtherUsualPain: $scope.datas.ATMOpenROtherUsualPain || null,
            ATMOpenLPractitionerClapping: $scope.datas.ATMOpenLPractitionerClapping  || null,
            ATMOpenLPractitionerCrackling: $scope.datas.ATMOpenLPractitionerCrackling || null,
            ATMOpenLPatientClapping: $scope.datas.ATMOpenLPatientClapping  || null,
            ATMOpenLPatientCrackling: $scope.datas.ATMOpenLPatientCrackling || null,
            ATMOpenLPatientPain: $scope.datas.ATMOpenLPatientPain || null,
            ATMOpenLCheckboxUsualPain: $scope.datas.ATMOpenLCheckboxUsualPain || null,
            ATMOpenLSelectUsualPain: $scope.datas.ATMOpenLSelectUsualPain|| null,
            ATMOpenLOtherUsualPain: $scope.datas.ATMOpenLOtherUsualPain || null,
            ATMCloseRPractitionerClapping: $scope.datas.ATMCloseRPractitionerClapping  || null,
            ATMCloseRPractitionerCrackling: $scope.datas.ATMCloseRPractitionerCrackling || null,
            ATMCloseRPatientClapping: $scope.datas.ATMCloseRPatientClapping  || null,
            ATMCloseRPatientCrackling: $scope.datas.ATMCloseRPatientCrackling || null,
            ATMCloseRPatientPain: $scope.datas.ATMCloseRPatientPain || null,
            ATMCloseRCheckboxUsualPain: $scope.datas.ATMCloseRCheckboxUsualPain || null,
            ATMCloseRSelectUsualPain: $scope.datas.ATMCloseRSelectUsualPain|| null,
            ATMCloseROtherUsualPain: $scope.datas.ATMCloseROtherUsualPain || null,
            ATMCloseLPractitionerClapping: $scope.datas.ATMCloseLPractitionerClapping  || null,
            ATMCloseLPractitionerCrackling: $scope.datas.ATMCloseLPractitionerCrackling || null,
            ATMCloseLPatientClapping: $scope.datas.ATMCloseLPatientClapping  || null,
            ATMCloseLPatientCrackling: $scope.datas.ATMCloseLPatientCrackling || null,
            ATMCloseLPatientPain: $scope.datas.ATMCloseLPatientPain || null,
            ATMCloseLCheckboxUsualPain: $scope.datas.ATMCloseLCheckboxUsualPain || null,
            ATMCloseLSelectUsualPain: $scope.datas.ATMCloseLSelectUsualPain|| null,
            ATMCloseLOtherUsualPain: $scope.datas.ATMCloseLOtherUsualPain || null,
            ATMLatLRPractitionerClapping: $scope.datas.ATMLatLRPractitionerClapping  || null,
            ATMLatLRPractitionerCrackling: $scope.datas.ATMLatLRPractitionerCrackling || null,
            ATMLatLRPatientClapping: $scope.datas.ATMLatLRPatientClapping  || null,
            ATMLatLRPatientCrackling: $scope.datas.ATMLatLRPatientCrackling || null,
            ATMLatLRPatientPain: $scope.datas.ATMLatLRPatientPain || null,
            ATMLatLRCheckboxUsualPain: $scope.datas.ATMLatLRCheckboxUsualPain || null,
            ATMLatLRSelectUsualPain: $scope.datas.ATMLatLRSelectUsualPain|| null,
            ATMLatLROtherUsualPain: $scope.datas.ATMLatLROtherUsualPain || null,
            ATMLatLLPractitionerClapping: $scope.datas.ATMLatLLPractitionerClapping  || null,
            ATMLatLLPractitionerCrackling: $scope.datas.ATMLatLLPractitionerCrackling || null,
            ATMLatLLPatientClapping: $scope.datas.ATMLatLLPatientClapping  || null,
            ATMLatLLPatientCrackling: $scope.datas.ATMLatLLPatientCrackling || null,
            ATMLatLLPatientPain: $scope.datas.ATMLatLLPatientPain || null,
            ATMLatLLCheckboxUsualPain: $scope.datas.ATMLatLLCheckboxUsualPain || null,
            ATMLatLLSelectUsualPain: $scope.datas.ATMLatLLSelectUsualPain|| null,
            ATMLatLLOtherUsualPain: $scope.datas.ATMLatLLOtherUsualPain || null,
            ATMLatRRPractitionerClapping: $scope.datas.ATMLatRRPractitionerClapping  || null,
            ATMLatRRPractitionerCrackling: $scope.datas.ATMLatRRPractitionerCrackling || null,
            ATMLatRRPatientClapping: $scope.datas.ATMLatRRPatientClapping  || null,
            ATMLatRRPatientCrackling: $scope.datas.ATMLatRRPatientCrackling || null,
            ATMLatRRPatientPain: $scope.datas.ATMLatRRPatientPain || null,
            ATMLatRRCheckboxUsualPain: $scope.datas.ATMLatRRCheckboxUsualPain || null,
            ATMLatRRSelectUsualPain: $scope.datas.ATMLatRRSelectUsualPain|| null,
            ATMLatRROtherUsualPain: $scope.datas.ATMLatRROtherUsualPain || null,
            ATMLatRLPractitionerClapping: $scope.datas.ATMLatRLPractitionerClapping  || null,
            ATMLatRLPractitionerCrackling: $scope.datas.ATMLatRLPractitionerCrackling || null,
            ATMLatRLPatientClapping: $scope.datas.ATMLatRLPatientClapping  || null,
            ATMLatRLPatientCrackling: $scope.datas.ATMLatRLPatientCrackling || null,
            ATMLatRLPatientPain: $scope.datas.ATMLatRLPatientPain || null,
            ATMLatRLCheckboxUsualPain: $scope.datas.ATMLatRLCheckboxUsualPain || null,
            ATMLatRLSelectUsualPain: $scope.datas.ATMLatRLSelectUsualPain|| null,
            ATMLatRLOtherUsualPain: $scope.datas.ATMLatRLOtherUsualPain || null,
            ATMPropRPractitionerClapping: $scope.datas.ATMPropRPractitionerClapping  || null,
            ATMPropRPractitionerCrackling: $scope.datas.ATMPropRPractitionerCrackling || null,
            ATMPropRPatientClapping: $scope.datas.ATMPropRPatientClapping  || null,
            ATMPropRPatientCrackling: $scope.datas.ATMPropRPatientCrackling || null,
            ATMPropRPatientPain: $scope.datas.ATMPropRPatientPain || null,
            ATMPropRCheckboxUsualPain: $scope.datas.ATMPropRCheckboxUsualPain || null,
            ATMPropRSelectUsualPain: $scope.datas.ATMPropRSelectUsualPain|| null,
            ATMPropROtherUsualPain: $scope.datas.ATMPropROtherUsualPain || null,
            ATMPropLPractitionerClapping: $scope.datas.ATMPropLPractitionerClapping  || null,
            ATMPropLPractitionerCrackling: $scope.datas.ATMPropLPractitionerCrackling || null,
            ATMPropLPatientClapping: $scope.datas.ATMPropLPatientClapping  || null,
            ATMPropLPatientCrackling: $scope.datas.ATMPropLPatientCrackling || null,
            ATMPropLPatientPain: $scope.datas.ATMPropLPatientPain || null,
            ATMPropLCheckboxUsualPain: $scope.datas.ATMPropLCheckboxUsualPain || null,
            ATMPropLSelectUsualPain: $scope.datas.ATMPropLSelectUsualPain|| null,
            ATMPropLOtherUsualPain: $scope.datas.ATMPropLOtherUsualPain || null,
            maxOpenPainOpen: $scope.datas.maxOpenPainOpen || null,
            maxOpenPainCausedR: $scope.datas.maxOpenPainCausedR || null,
            maxOpenSamePainR: $scope.datas.maxOpenSamePainR || null,
            maxOpenSelectR: $scope.datas.maxOpenSelectR || null,
            maxOpenOtherInputR: $scope.datas.maxOpenOtherInputR || null,
            maxOpenPainCausedL: $scope.datas.maxOpenPainCausedL || null,
            maxOpenSamePainL: $scope.datas.maxOpenSamePainL || null,
            maxOpenSelectL: $scope.datas.maxOpenSelectL || null,
            maxOpenOtherInputL: $scope.datas.maxOpenOtherInputL || null,
            maxOpenAssistedPainOpen: $scope.datas.maxOpenAssistedPainOpen || null,
            maxOpenAssistedPainCausedR: $scope.datas.maxOpenAssistedPainCausedR || null,
            maxOpenAssistedSamePainR: $scope.datas.maxOpenAssistedSamePainR || null,
            maxOpenAssistedSelectR: $scope.datas.maxOpenAssistedSelectR || null,
            maxOpenAssistedOtherInputR: $scope.datas.maxOpenAssistedOtherInputR || null,
            maxOpenAssistedPainCausedL: $scope.datas.maxOpenAssistedPainCausedL || null,
            maxOpenAssistedSamePainL: $scope.datas.maxOpenAssistedSamePainL || null,
            maxOpenAssistedSelectL: $scope.datas.maxOpenAssistedSelectL || null,
            maxOpenAssistedOtherInputL: $scope.datas.maxOpenAssistedOtherInputL || null,
            resistanceOpenPainOpen: $scope.datas.resistanceOpenPainOpen || null,
            resistanceOpenPainCausedR: $scope.datas.resistanceOpenPainCausedR || null,
            resistanceOpenSamePainR: $scope.datas.resistanceOpenSamePainR || null,
            resistanceOpenSelectR: $scope.datas.resistanceOpenSelectR || null,
            resistanceOpenOtherInputR: $scope.datas.resistanceOpenOtherInputR || null,
            resistanceOpenPainCausedL: $scope.datas.resistanceOpenPainCausedL || null,
            resistanceOpenSamePainL: $scope.datas.resistanceOpenSamePainL || null,
            resistanceOpenSelectL: $scope.datas.resistanceOpenSelectL || null,
            resistanceOpenOtherInputL: $scope.datas.resistanceOpenOtherInputL || null,
            resistanceClosePainOpen: $scope.datas.resistanceClosePainOpen || null,
            resistanceClosePainCausedR: $scope.datas.resistanceClosePainCausedR || null,
            resistanceCloseSamePainR: $scope.datas.resistanceCloseSamePainR || null,
            resistanceCloseSelectR: $scope.datas.resistanceCloseSelectR || null,
            resistanceCloseOtherInputR: $scope.datas.resistanceCloseOtherInputR || null,
            resistanceClosePainCausedL: $scope.datas.resistanceClosePainCausedL || null,
            resistanceCloseSamePainL: $scope.datas.resistanceCloseSamePainL || null,
            resistanceCloseSelectL: $scope.datas.resistanceCloseSelectL || null,
            resistanceCloseOtherInputL: $scope.datas.resistanceCloseOtherInputL || null,
            latRPainOpen: $scope.datas.latRPainOpen || null,
            latRPainCausedR: $scope.datas.latRPainCausedR || null,
            latRSamePainR: $scope.datas.latRSamePainR || null,
            latRSelectR: $scope.datas.latRSelectR || null,
            latROtherInputR: $scope.datas.latROtherInputR || null,
            latRPainCausedL: $scope.datas.latRPainCausedL || null,
            latRSamePainL: $scope.datas.latRSamePainL || null,
            latRSelectL: $scope.datas.latRSelectL || null,
            latROtherInputL: $scope.datas.latROtherInputL || null,
            latRassistedPainOpen: $scope.datas.latRassistedPainOpen || null,
            latRassistedPainCausedR: $scope.datas.latRassistedPainCausedR || null,
            latRassistedSamePainR: $scope.datas.latRassistedSamePainR || null,
            latRassistedSelectR: $scope.datas.latRassistedSelectR || null,
            latRassistedOtherInputR: $scope.datas.latRassistedOtherInputR || null,
            latRassistedPainCausedL: $scope.datas.latRassistedPainCausedL || null,
            latRassistedSamePainL: $scope.datas.latRassistedSamePainL || null,
            latRassistedSelectL: $scope.datas.latRassistedSelectL || null,
            latRassistedOtherInputL: $scope.datas.latRassistedOtherInputL || null,
            resistanceLatRPainOpen: $scope.datas.resistanceLatRPainOpen || null,
            resistanceLatRPainCausedR: $scope.datas.resistanceLatRPainCausedR || null,
            resistanceLatRSamePainR: $scope.datas.resistanceLatRSamePainR || null,
            resistanceLatRSelectR: $scope.datas.resistanceLatRSelectR || null,
            resistanceLatROtherInputR: $scope.datas.resistanceLatROtherInputR || null,
            resistanceLatRPainCausedL: $scope.datas.resistanceLatRPainCausedL || null,
            resistanceLatRSamePainL: $scope.datas.resistanceLatRSamePainL || null,
            resistanceLatRSelectL: $scope.datas.resistanceLatRSelectL || null,
            resistanceLatROtherInputL: $scope.datas.resistanceLatROtherInputL || null,
            latLassistedPainOpen: $scope.datas.latLassistedPainOpen || null,
            latLassistedPainCausedR: $scope.datas.latLassistedPainCausedR || null,
            latLassistedSamePainR: $scope.datas.latLassistedSamePainR || null,
            latLassistedSelectR: $scope.datas.latLassistedSelectR || null,
            latLassistedOtherInputR: $scope.datas.latLassistedOtherInputR || null,
            latLassistedPainCausedL: $scope.datas.latLassistedPainCausedL || null,
            latLassistedSamePainL: $scope.datas.latLassistedSamePainL || null,
            latLassistedSelectL: $scope.datas.latLassistedSelectL || null,
            latLassistedOtherInputL: $scope.datas.latLassistedOtherInputL || null,
            resistanceLatLPainOpen: $scope.datas.resistanceLatLPainOpen || null,
            resistanceLatLPainCausedR: $scope.datas.resistanceLatLPainCausedR || null,
            resistanceLatLSamePainR: $scope.datas.resistanceLatLSamePainR || null,
            resistanceLatLSelectR: $scope.datas.resistanceLatLSelectR || null,
            resistanceLatLOtherInputR: $scope.datas.resistanceLatLOtherInputR || null,
            resistanceLatLPainCausedL: $scope.datas.resistanceLatLPainCausedL || null,
            resistanceLatLSamePainL: $scope.datas.resistanceLatLSamePainL || null,
            resistanceLatLSelectL: $scope.datas.resistanceLatLSelectL || null,
            resistanceLatLOtherInputL: $scope.datas.resistanceLatLOtherInputL || null,
            tablePropulsionPainOpen: $scope.datas.tablePropulsionPainOpen || null,
            tablePropulsionPainCausedR: $scope.datas.tablePropulsionPainCausedR || null,
            tablePropulsionSamePainR: $scope.datas.tablePropulsionSamePainR || null,
            tablePropulsionSelectR: $scope.datas.tablePropulsionSelectR || null,
            tablePropulsionOtherInputR: $scope.datas.tablePropulsionOtherInputR || null,
            tablePropulsionPainCausedL: $scope.datas.tablePropulsionPainCausedL || null,
            tablePropulsionSamePainL: $scope.datas.tablePropulsionSamePainL || null,
            tablePropulsionSelectL: $scope.datas.tablePropulsionSelectL || null,
            tablePropulsionOtherInputL: $scope.datas.tablePropulsionOtherInputL || null,
            resistancePropPainOpen: $scope.datas.resistancePropPainOpen || null,
            resistancePropPainCausedR: $scope.datas.resistancePropPainCausedR || null,
            resistancePropSamePainR: $scope.datas.resistancePropSamePainR || null,
            resistancePropSelectR: $scope.datas.resistancePropSelectR || null,
            resistancePropOtherInputR: $scope.datas.resistancePropOtherInputR || null,
            resistancePropPainCausedL: $scope.datas.resistancePropPainCausedL || null,
            resistancePropSamePainL: $scope.datas.resistancePropSamePainL || null,
            resistancePropSelectL: $scope.datas.resistancePropSelectL || null,
            resistancePropOtherInputL: $scope.datas.resistancePropOtherInputL || null,
            palpationMuscles: $scope.datas.palpationMuscles  || null,
            painOpen: $scope.datas.noPainOpen  || null,
            headache: $scope.datas.headache  || null,
            whichMotionHeadache: $scope.datas.whichMotionHeadache  || null,
            tmpPostPainCausedR: $scope.datas.tmpPostPainCausedR || null,
            tmpPostSamePainR: $scope.datas.tmpPostSamePainR || null,
            tmpPostSelectR: $scope.datas.tmpPostSelectR || null,
            tmpPostOtherInputR: $scope.datas.tmpPostOtherInputR || null,
            tmpPostPainCausedL: $scope.datas.tmpPostPainCausedL || null,
            tmpPostSamePainL: $scope.datas.tmpPostSamePainL || null,
            tmpPostSelectL: $scope.datas.tmpPostSelectL || null,
            tmpPostOtherInputL: $scope.datas.tmpPostOtherInputL || null,
            tmpAvgPainCausedR: $scope.datas.tmpAvgPainCausedR || null,
            tmpAvgSamePainR: $scope.datas.tmpAvgSamePainR || null,
            tmpAvgSelectR: $scope.datas.tmpAvgSelectR || null,
            tmpAvgOtherInputR: $scope.datas.tmpAvgOtherInputR || null,
            tmpAvgPainCausedL: $scope.datas.tmpAvgPainCausedL || null,
            tmpAvgSamePainL: $scope.datas.tmpAvgSamePainL || null,
            tmpAvgSelectL: $scope.datas.tmpAvgSelectL || null,
            tmpAvgOtherInputL: $scope.datas.tmpAvgOtherInputL || null,
            tmpAntPainCausedR: $scope.datas.tmpAntPainCausedR || null,
            tmpAntSamePainR: $scope.datas.tmpAntSamePainR || null,
            tmpAntSelectR: $scope.datas.tmpAntSelectR || null,
            tmpAntOtherInputR: $scope.datas.tmpAntOtherInputR || null,
            tmpAntPainCausedL: $scope.datas.tmpAntPainCausedL || null,
            tmpAntSamePainL: $scope.datas.tmpAntSamePainL || null,
            tmpAntSelectL: $scope.datas.tmpAntSelectL || null,
            tmpAntOtherInputL: $scope.datas.tmpAntOtherInputL || null,
            massageAnglePainCausedR: $scope.datas.massageAnglePainCausedR || null,
            massageAngleSamePainR: $scope.datas.massageAngleSamePainR || null,
            massageAngleSelectR: $scope.datas.massageAngleSelectR || null,
            massageAngleOtherInputR: $scope.datas.massageAngleOtherInputR || null,
            massageAnglePainCausedL: $scope.datas.massageAnglePainCausedL || null,
            massageAngleSamePainL: $scope.datas.massageAngleSamePainL || null,
            massageAngleSelectL: $scope.datas.massageAngleSelectL || null,
            massageAngleOtherInputL: $scope.datas.massageAngleOtherInputL || null,
            massageBodyPainCausedR: $scope.datas.massageBodyPainCausedR || null,
            massageBodySamePainR: $scope.datas.massageBodySamePainR || null,
            massageBodySelectR: $scope.datas.massageBodySelectR || null,
            massageBodyOtherInputR: $scope.datas.massageBodyOtherInputR || null,
            massageBodyPainCausedL: $scope.datas.massageBodyPainCausedL || null,
            massageBodySamePainL: $scope.datas.massageBodySamePainL || null,
            massageBodySelectL: $scope.datas.massageBodySelectL || null,
            massageBodyOtherInputL: $scope.datas.massageBodyOtherInputL || null,
            massageInsertPainCausedR: $scope.datas.massageInsertPainCausedR || null,
            massageInsertSamePainR: $scope.datas.massageInsertSamePainR || null,
            massageInsertSelectR: $scope.datas.massageInsertSelectR || null,
            massageInsertOtherInputR: $scope.datas.massageInsertOtherInputR || null,
            massageInsertPainCausedL: $scope.datas.massageInsertPainCausedL || null,
            massageInsertSamePainL: $scope.datas.massageInsertSamePainL || null,
            massageInsertSelectL: $scope.datas.massageInsertSelectL || null,
            massageInsertOtherInputL: $scope.datas.massageInsertOtherInputL || null,
            sidePolePainCausedR: $scope.datas.sidePolePainCausedR || null,
            sidePoleSamePainR: $scope.datas.sidePoleSamePainR || null,
            sidePoleSelectR: $scope.datas.sidePoleSelectR || null,
            sidePoleOtherInputR: $scope.datas.sidePoleOtherInputR || null,
            sidePolePainCausedL: $scope.datas.sidePolePainCausedL || null,
            sidePoleSamePainL: $scope.datas.sidePoleSamePainL || null,
            sidePoleSelectL: $scope.datas.sidePoleSelectL || null,
            sidePoleOtherInputL: $scope.datas.sidePoleOtherInputL || null,
            aroundPolePainCausedR: $scope.datas.aroundPolePainCausedR || null,
            aroundPoleSamePainR: $scope.datas.aroundPoleSamePainR || null,
            aroundPoleSelectR: $scope.datas.aroundPoleSelectR || null,
            aroundPoleOtherInputR: $scope.datas.aroundPoleOtherInputR || null,
            aroundPolePainCausedL: $scope.datas.aroundPolePainCausedL || null,
            aroundPoleSamePainL: $scope.datas.aroundPoleSamePainL || null,
            aroundPoleSelectL: $scope.datas.aroundPoleSelectL || null,
            aroundPoleOtherInputL: $scope.datas.aroundPoleOtherInputL || null,
            otherMuscleMasticatorsPainCausedR: $scope.datas.otherMuscleMasticatorsPainCausedR || null,
            otherMuscleMasticatorsSamePainR: $scope.datas.otherMuscleMasticatorsSamePainR || null,
            otherMuscleMasticatorsSelectR: $scope.datas.otherMuscleMasticatorsSelectR || null,
            otherMuscleMasticatorsOtherInputR: $scope.datas.otherMuscleMasticatorsOtherInputR || null,
            otherMuscleMasticatorsPainCausedL: $scope.datas.otherMuscleMasticatorsPainCausedL || null,
            otherMuscleMasticatorsSamePainL: $scope.datas.otherMuscleMasticatorsSamePainL || null,
            otherMuscleMasticatorsSelectL: $scope.datas.otherMuscleMasticatorsSelectL || null,
            otherMuscleMasticatorsOtherInputL: $scope.datas.otherMuscleMasticatorsOtherInputL || null,
            digastricMDPainCausedR: $scope.datas.digastricMDPainCausedR || null,
            digastricMDSamePainR: $scope.datas.digastricMDSamePainR || null,
            digastricMDSelectR: $scope.datas.digastricMDSelectR || null,
            digastricMDOtherInputR: $scope.datas.digastricMDOtherInputR || null,
            digastricMDPainCausedL: $scope.datas.digastricMDPainCausedL || null,
            digastricMDSamePainL: $scope.datas.digastricMDSamePainL || null,
            digastricMDSelectL: $scope.datas.digastricMDSelectL || null,
            digastricMDOtherInputL: $scope.datas.digastricMDOtherInputL || null,
            PterygoidMedialPainCausedR: $scope.datas.PterygoidMedialPainCausedR || null,
            PterygoidMedialSamePainR: $scope.datas.PterygoidMedialSamePainR || null,
            PterygoidMedialSelectR: $scope.datas.PterygoidMedialSelectR || null,
            PterygoidMedialOtherInputR: $scope.datas.PterygoidMedialOtherInputR || null,
            PterygoidMedialPainCausedL: $scope.datas.PterygoidMedialPainCausedL || null,
            PterygoidMedialSamePainL: $scope.datas.PterygoidMedialSamePainL || null,
            PterygoidMedialSelectL: $scope.datas.PterygoidMedialSelectL || null,
            PterygoidMedialOtherInputL: $scope.datas.PterygoidMedialOtherInputL || null,
            PterygoidAreaSidePainCausedR: $scope.datas.PterygoidAreaSidePainCausedR || null,
            PterygoidAreaSideSamePainR: $scope.datas.PterygoidAreaSideSamePainR || null,
            PterygoidAreaSideSelectR: $scope.datas.PterygoidAreaSideSelectR || null,
            PterygoidAreaSideOtherInputR: $scope.datas.PterygoidAreaSideOtherInputR || null,
            PterygoidAreaSidePainCausedL: $scope.datas.PterygoidAreaSidePainCausedL || null,
            PterygoidAreaSideSamePainL: $scope.datas.PterygoidAreaSideSamePainL || null,
            PterygoidAreaSideSelectL: $scope.datas.PterygoidAreaSideSelectL || null,
            PterygoidAreaSideOtherInputL: $scope.datas.PterygoidAreaSideOtherInputL || null,
            TendonTmpPainCausedR: $scope.datas.TendonTmpPainCausedR || null,
            TendonTmpSamePainR: $scope.datas.TendonTmpSamePainR || null,
            TendonTmpSelectR: $scope.datas.TendonTmpSelectR || null,
            TendonTmpOtherInputR: $scope.datas.TendonTmpOtherInputR || null,
            TendonTmpPainCausedL: $scope.datas.TendonTmpPainCausedL || null,
            TendonTmpSamePainL: $scope.datas.TendonTmpSamePainL || null,
            TendonTmpSelectL: $scope.datas.TendonTmpSelectL || null,
            TendonTmpOtherInputL: $scope.datas.TendonTmpOtherInputL || null,
            otherMusclesCervicoPainCausedR: $scope.datas.otherMusclesCervicoPainCausedR || null,
            otherMusclesCervicoSamePainR: $scope.datas.otherMusclesCervicoSamePainR || null,
            otherMusclesCervicoSelectR: $scope.datas.otherMusclesCervicoSelectR || null,
            otherMusclesCervicoOtherInputR: $scope.datas.otherMusclesCervicoOtherInputR || null,
            otherMusclesCervicoPainCausedL: $scope.datas.otherMusclesCervicoPainCausedL || null,
            otherMusclesCervicoSamePainL: $scope.datas.otherMusclesCervicoSamePainL || null,
            otherMusclesCervicoSelectL: $scope.datas.otherMusclesCervicoSelectL || null,
            otherMusclesCervicoOtherInputL: $scope.datas.otherMusclesCervicoOtherInputL || null,
            mastoidSidePainCausedR: $scope.datas.mastoidSidePainCausedR || null,
            mastoidSideSamePainR: $scope.datas.mastoidSideSamePainR || null,
            mastoidSideSelectR: $scope.datas.mastoidSideSelectR || null,
            mastoidSideOtherInputR: $scope.datas.mastoidSideOtherInputR || null,
            mastoidSidePainCausedL: $scope.datas.mastoidSidePainCausedL || null,
            mastoidSideSamePainL: $scope.datas.mastoidSideSamePainL || null,
            mastoidSideSelectL: $scope.datas.mastoidSideSelectL || null,
            mastoidSideOtherInputL: $scope.datas.mastoidSideOtherInputL || null,
            tableTrapezePainCausedR: $scope.datas.tableTrapezePainCausedR || null,
            tableTrapezeSamePainR: $scope.datas.tableTrapezeSamePainR || null,
            tableTrapezeSelectR: $scope.datas.tableTrapezeSelectR || null,
            tableTrapezeOtherInputR: $scope.datas.tableTrapezeOtherInputR || null,
            tableTrapezePainCausedL: $scope.datas.tableTrapezePainCausedL || null,
            tableTrapezeSamePainL: $scope.datas.tableTrapezeSamePainL || null,
            tableTrapezeSelectL: $scope.datas.tableTrapezeSelectL || null,
            tableTrapezeOtherInputL: $scope.datas.tableTrapezeOtherInputL || null
          });
        }
        $scope.loading = false;
      });
    }

    $scope.toggleDiv = function(key){
      $scope[key] = !$scope[key];
    }

    $scope.headers = [
      {
        label: 'Identifiant du patient :',
        type: 'text',
        key: 'patientId'
      },
      {
        label: 'Date de naissance :',
        type: 'date',
        key: 'birthdate'
      },
      {
        label: 'Date de consultation :',
        type: 'date',
        key: 'date'
      },
      {
        label: 'Profession :',
        type: 'text',
        key: 'profession'
      }
    ]

    $scope.pain1 = [
      {
        label: ' Evaluation: Fond Douloureux',
        scale: numbers,
        key: 'bottom'
      },
      {
        label: 'Evaluation: Pic Douloureux',
        scale: numbers,
        key: 'peak'
      }
    ]

    $scope.pain2 = [
      {
        label: 'Qualité',
        key: 'quality'
      },
      {
        label: 'Durée ',
        key: 'time'
      },
      {
        label: 'Frequence',
        key: 'frequency'
      },
      {
        label: 'Circonstance de début',
        key: 'startingCycle'
      },
      {
        label: 'Modifié par',
        key: 'modifiedBy'
      },
      {
        label: 'Traitement',
        key: 'treatment'
      },
    ]

    $scope.environment = [
      {
        label: 'Familial :',
        key: 'family'
      },
      {
        label: 'Social :',
        key: 'social'
      },
      {
        label: 'Professionnel :',
        key: 'professional'
      },
    ]

    $scope.bucal = [
      {
        label: 'Interférence(s) en latéralité droite :',
        key: 'lateralRight'
      },
      {
        label: 'Interférence(s) en latéralité gauche :',
        key: 'lateralLeft'
      },
      {
        label: 'Interférence(s) en propulsion :',
        key: 'propulsion'
      },
      {
        label: 'Prématurité(s) :',
        key: 'prematured'
      }
    ]

    $scope.wear = [
      {
        label: 'Erosion dents : ',
        key: 'erosion'
      },
      {
        label: 'Attrition dents :',
        key: 'attrition'
      },
      {
        label: 'Abrasion dents :',
        key: 'abrasion'
      }
    ]

    $scope.plause = ["possible", "probable", "defini"];

    $scope.label_partie_17  = [
      {
        label: 'Bâtonnet',
        position: 'Droite',
        key: 'stickR'
      },
      {
        label: '',
        position: 'Gauche',
        key: 'stickL'
      }
    ];

    //titre + position + name
    //ya des blanc car des lignes de tableau ne contiennent pas de titre

    $scope.label_partie_15  = [
      {
        label: 'Ouverture',
        position: 'ATM Droite',
        key: 'ATMOpenR'
      },
      {
        label: '',
        position: 'ATM Gauche',
        key: 'ATMOpenL'
      },
      {
        label: 'Fermeture',
        position: 'ATM droite',
        key: 'ATMCloseR'
      },
      {
        label: '',
        position: 'ATM Gauche',
        key: 'ATMCloseL'
      },
      {
        label: 'Latérité gauche',
        position: 'ATM droite',
        key: 'ATMLatLR'
      },
      {
        label: '',
        position: 'ATM gauche',
        key: 'ATMLatLL'
      },
      {
        label: 'Latérité droite',
        position: 'ATM droite',
        key: 'ATMLatRR'
      },
      {
        label: '',
        position: 'ATM gauche',
        key: 'ATMLatRL'
      },
      {
        label: 'Propulsion',
        position: 'ATM droite',
        key: 'ATMPropR'
      },
      {
        label: '',
        position: 'ATM gauche',
        key: 'ATMPropL'
      }
    ];

    $scope.titre_tableau_douleur =
    [
      "Douleur provoquée",
      "Est-elle identique à la douleur habituelle ?",
      "Douleur(s) référée(s)"
    ];

    $scope.scale = ['Oui', 'Non'];

    $scope.label_partie_13  = [
      {
        label: 'Ouv. max. non assistée :',
        showInput: true,
        key: 'maxOpen'
      },
      {
        label: 'Ouv. max. assistée :',
        showInput: true,
        key: 'maxOpenAssisted'
      },
      {
        label: 'Ouv. contre résistance :',
        showInput: false,
        key: 'resistanceOpen'
      },
      {
        label: 'Fermeture contre résistance :',
        showInput: false,
        key: 'resistanceClose'
      },
      {
        label: 'Latéralité droite :',
        showInput: true,
        key: 'latR'
      },
      {
        label: 'Latéralité droite assistée:',
        showInput: true,
        key: 'latRassisted'
      },
      {
        label: 'Latéralité droite contre résistance :',
        showInput: false,
        key: 'resistanceLatR'
      },
      {
        label: 'Latéralité gauche :',
        showInput: true,
        key: 'latL'
      },
      {
        label: 'Latéralité gauche assistée:',
        showInput: true,
        key: 'latLassisted'
      },
      {
        label: 'Latéralité gauche contre résistance :',
        showInput: false,
        key: 'resistanceLatL'
      },
      {
        label: 'Propulsion :',
        showInput: true,
        key: 'tablePropulsion'
      },
      {
        label: 'Propulsion contre résistance :',
        showInput: false,
        key: 'resistanceProp'
      }
    ];

    $scope.douleurReferee1 = [
      {
        label: 'Temporal postérieur',
        showInput:true,
        key: 'tmpPost'
      },
      {
        label: 'Temporal moyen',
        showInput:true,
        key: 'tmpAvg'
      },
      {
        label: 'Temporal antérieur',
        showInput:true,
        key: 'tmpAnt'
      }
    ];

    $scope.douleurReferee2 = [
      {
        label: 'Masséter (origine angle mdb)',
        showInput:true,
        key: 'massageAngle'
      },
      {
        label: 'Masséter (corps)',
        showInput:true,
        key: 'massageBody'
      },
      {
        label: 'Masséter (insertion zygomatique)',
        showInput:true,
        key: 'massageInsert'
      }
    ];


    $scope.localisationATM = [
      {
        label: 'ATM',
        showInput:false,
        key: 'atm'
      },
      {
        label: 'Pôle latéral 0,5 kg',
        showInput:true,
        key: 'sidePole'
      },
      {
        label: 'Autour du pôle latéral 1 kg',
        showInput:true,
        key: 'aroundPole'
      },
      {
        label: 'Autres muscles masticateurs',
        showInput:true,
        key: 'otherMuscleMasticators'
      },
      {
        label: 'Digastrique (région md post)',
        showInput:true,
        key: 'digastricMD'
      },
      {
        label: 'Ptérygoïdien médial (région submd)',
        showInput:true,
        key: 'PterygoidMedial'
      },
      {
        label: 'Aire du ptérygoïdien latéral',
        showInput:true,
        key: 'PterygoidAreaSide'
      },
      {
        label: 'Tendon du temporal',
        showInput:true,
        key: 'TendonTmp'
      },
      {
        label: 'Autres muscles cervico-scapulaires 0,5 kg',
        showInput:false,
        key: 'otherMusclesCervico'
      },
      {
        label: 'Sterno-cléido-mastoïdien latéral',
        showInput:true,
        key: 'mastoidSide'
      },
      {
        label: 'Trapèze',
        showInput:true,
        key: 'tableTrapeze'
      }
    ];


    $scope.localisationMuscle = [
      "M. temporal droit",
      "M. temporal gauche",
      "M. masséter droit",
      "M. masséter gauche",
      "Atm droite",
      "Atm gauche",
      "Autres"
    ];
  }
}

export default angular.module('toothrushApp.general', [uiRouter])
  .config(routes)
  .component('general', {
    template: require('./general.pug'),
    controller: GeneralComponent,
    controllerAs: 'generalCtrl'
  })
  .name;
